apiVersion: apps/v1
kind: Deployment
metadata:
  name: two-tier-app
  labels:
    app: two-tier-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: two-tier-app
  template:
    metadata:
      labels:
        app: two-tier-app
    spec:
      containers:
        - name: two-tier-app
          image: shubzz/flaskapp:latest
          env:
            - name: MYSQL_HOST
              value: "flask-mysql-do-user-19593871-0.k.db.ondigitalocean.com"          # this is your mysql's service clusture IP, Make sure to change it with yours
            - name: MYSQL_PORT
              value: "25060" 
            - name: MYSQL_PASSWORD
              value: "AVNS_F4ZybpE0HifgRBFYsOu"
            - name: MYSQL_USER
              value: "doadmin"
            - name: MYSQL_DB
              value: "defaultdb"
          ports:
            - containerPort: 5000
          imagePullPolicy: Always


---
apiVersion: v1
kind: Service
metadata:
  name: two-tier-app-service
spec:
  selector:
    app: two-tier-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer # type of the service.
